CREATE TABLE IF NOT EXISTS admin_audit (
 id BIGINT AUTO_INCREMENT PRIMARY KEY, guild_id BIGINT UNSIGNED NOT NULL, actor_id BIGINT UNSIGNED NOT NULL, action VARCHAR(100) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, INDEX idx_audit_guild_date (guild_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
